import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react'
import { StringLiteralType } from 'typescript'

const inter = Inter({ subsets: ['latin'] })

interface Exam {
  subject: string,
  paper: string, 
  date:string,
  topics:string[]
}
export default function Home() {

  const exam_dates:Exam[] = [{
    subject: "Economics",
    paper: "Paper 1",
    date: "05/18/2023",
    topics: ["Theme 1", "Theme 3"]
  },{
    subject: "Economics",
    paper: "Paper 2",
    date: "05/22/2023",
    topics: ["Theme 2", "Theme 4"]
  },{
    subject: "Physics",
    paper: "Paper 1",
    date: "05/24/2023",
    topics: ["Module 1", "Module 2", "Module 3", "Module 5"]
  },{
    subject: "Further Maths",
    paper: "Paper 1",
    date: "05/25/2023",
    topics: ["All pure topics"]
  },{
    subject: "Economics",
    paper: "Paper 3",
    date: "06/05/2023",
    topics: ["All themes"]
  },{
    subject: "Further Maths",
    paper: "Paper 2",
    date: "06/05/2023",
    topics: ["All pure topics"]
  },{
    subject: "Physics",
    paper: "Paper 2",
    date: "06/09/2023",
    topics: ["Module 1", "Module 2", "Module 4", "Module 6"]
  },{
    subject: "Further Maths",
    paper: "Paper 3",
    date: "06/14/2023",
    topics: ["Mechanics", "Statistics"]
  },{
    subject: "Physics",
    paper: "Paper 3",
    date: "06/15/2023",
    topics: ["All modules"]
  }]

  useEffect(()=>{

  }, [])

  return (
    <>
      <Head>
        <title>Exam Counter | Count how many days you have left</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/bell.ico" />
      </Head>
      <div className='max-w-5xl m-auto h-96 my-5'>
        <h1 className='font-extralight text-center font-poppins text-4xl mt-5 underline'>Exam Counter</h1>
        <div className='flex mt-5 underline flex-col mx-3 font-poppins font-bold'>
          <a className='text-red-900' target="_blank" href="https://qualifications.pearson.com/content/dam/pdf/A%20Level/Economics/2015/specification-and-sample-assessment-materials/A_Level_Econ_A_Spec.pdf">Click here for Economics Spec</a>
          <a className='text-purple-900' target="_blank" href="https://www.ocr.org.uk/Images/171726-specification-accredited-a-level-gce-physics-a-h556.pdf">Click here for Physics Spec</a>
          <a className='text-blue-900' target="_blank" href="https://filestore.aqa.org.uk/resources/mathematics/specifications/AQA-7367-SP-2017.PDF">Click here for Further Maths Spec</a>
        </div>
        <div className='flex mt-5 pb-10 flex-col rounded-sm font-poppins text-white'>
          {
            exam_dates.map((exam, index)=>{
              let date_1 = new Date(exam.date)
              let date_2 = new Date()
              let difference = date_1.getTime() - date_2.getTime()
              let totalDays = Math.ceil(difference / (1000 * 3600 * 24))

              if(exam.subject==="Economics") {
                return(
                  <div key={index} className='bg-red-500 text-2xl shadow-2xl p-4 m-3 rounded-sm mx-3'>
                    <h1 className='font-bold'>{exam.subject}</h1>
                    <h1 className=''>{exam.paper}</h1>
                    <h1>{totalDays} days left to go!</h1>
                    <div className='flex flex-row mt-2'>
                      <h1>Revise:</h1> 
                      {
                        exam.topics.map((topic, index)=>(
                          <div key={index} className='ml-4 p-1 rounded-md bg-red-900'>
                            {topic}
                          </div>
                        ))
                      }
                    </div>
                  </div>
                )
              }
              if(exam.subject=="Physics") {
                return(
                <div key={index} className='text-2xl bg-purple-500 shadow-2xl p-4 m-3 rounded-sm mx-3'>
                  <h1 className='font-bold'>{exam.subject}</h1>
                  <h1 className=''>{exam.paper}</h1>
                  <h1>{totalDays} days left to go!</h1>
                  <div className='flex flex-row mt-2'>
                      <h1>Revise:</h1> 
                      {
                        exam.topics.map((topic,index)=>(
                          <div key={index} className='ml-4 p-1 rounded-md bg-purple-900'>
                            {topic}
                          </div>
                        ))
                      }
                    </div>
                </div>
                ) 
              }
              else{
                return(
                  <div key={index} className='text-2xl shadow-2xl bg-blue-500 p-4 m-3 rounded-sm mx-3'>
                    <h1 className='font-bold'>{exam.subject}</h1>
                    <h1 className=''>{exam.paper}</h1>
                    <h1>{totalDays} days left to go!</h1>
                    <div className='flex flex-row mt-2'>
                      <h1>Revise:</h1> 
                      {
                        exam.topics.map((topic, index)=>(
                          <div key={index} className='ml-4 p-1 rounded-md bg-blue-900'>
                            {topic}
                          </div>
                        ))
                      }
                    </div>
                  </div>
                )  
              }
            })
          }
        </div>
      </div>
    </>
  )
}
